version: '3'
volumes:
  bundle:
    driver: 'local'
  bundle_install:
    driver: 'local'
  log:
    driver: 'local'
  mysql-data:
    driver: 'local'
  node_modules:
    driver: 'local'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - '13306:3306'
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot", "-P", "3306"]
      interval: 1m
      timeout: 10s
      retries: 5
  app:
    build: ./docker
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/app/.bundle
      - bundle_install:/app/vendor/bundle
      - node_modules:/app/node_modules
      - log:/app/log
    ports:
      - '3000:3000'
    networks:
      - default
    depends_on:
      - db
