default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: db
  port: 3306
  username: root

development:
  <<: *default
  database: webpackeractioncable_development

test:
  <<: *default
  database: webpackeractioncable_test
